version: '3.4'

networks:
  webnet:

services:
  hello-service:
    image: com.elemfra.test/local-project:0.0.1-SNAPSHOT
    deploy:
      replicas: 5
    ports:
      - "8080:8080"
    networks:
      - webnet